// ════════════════════════════════════════
// Sensei policy sets (FU-4).
//
// Two STATIC, named sets that the sensei permission model derives from, kept in
// one leaf module (no imports) so there is a single source of truth and no
// import cycle. The FU-4 root cause is a hand-maintained allow-list that
// silently under-grants a trusted, open-ended agent every time a new tool ships;
// the mirror-image failure is a hand-maintained DENY-list that silently
// UNDER-blocks when a new dangerous tool ships. Both are avoided by classifying
// against a stable named set instead of remembering to edit a list per feature.
// ════════════════════════════════════════

/**
 * Comms-to-people tools: every tool that reaches a real person on one of the
 * owner's channels (email / Teams / SMS / iMessage / voice), including the
 * user-slot (`user_*`) send/reply/forward variants. This is the single named
 * set the Trainer's deny-list derives from, so a FUTURE comms tool is denied by
 * construction, add it here and the Trainer refresh picks it up on the next boot
 * (ensureTrainerAgentRunning rewrites tools_policy every boot). The set is the
 * whole comms-to-people surface (sends plus the auxiliary contact-list / call
 * lifecycle + status tools on those channels), matching the owner decision to
 * block the Trainer from the owner's comms-to-people channels while keeping
 * send_to_agent and in-chat replies.
 *
 * NOTE: most of these are ALSO hard primary-only gated inside executeToolInner
 * today (imessage/sms/voice at the dispatch guards; the Google/Microsoft write
 * tools at their belt-and-suspenders isPrimaryAgent checks), so the deny is
 * defense-in-depth for the ones that are already gated and the real enforcement
 * for any that are not. Listing every one keeps the surface honest.
 *
 * HAND-PICKED, and legitimately so: this is a SECURITY surface that is BROADER
 * than any single classifier, it includes non-send comms tools (imessage_list_
 * contacts, voice_call_end/status) that no effect/channel classifier would flag.
 * So it cannot simply be replaced by a derivation. Instead the drift risk is
 * pinned by the tool-list conformance tripwire (server test + release gate),
 * which now enforces THREE things and fails the build on any of them:
 *   (a) every name here resolves to a REAL tool (a rename fails);
 *   (b) EXHAUSTIVE full-registry accounting, every base tool in the registry is
 *       either listed here (a deny) or matched by the SEND_TO_PEOPLE_NA ledger
 *       below (an explicit not-applicable decision with a reason). A NEW tool that
 *       nobody classified fails the build naming the tool, so an OMISSION (a comms
 *       tool that should be denied but was forgotten) is as loud as a phantom, not
 *       a silent under-block. This is the anti-omission half added 2026-07-08;
 *   (c) user_ send-twin parity (USER_TWINNED_SEND_PREFIXES below): every denied
 *       base send in a family that generates owner-account twins also has its
 *       user_ twin denied. This is what surfaced the user_teams_* sends that had
 *       been silently missing here.
 */
export const SEND_TO_PEOPLE: readonly string[] = [
  // Gmail (agent slot + user slot)
  'gmail_send', 'gmail_reply', 'gmail_forward',
  'user_gmail_send', 'user_gmail_reply', 'user_gmail_forward',
  // Outlook (agent slot + user slot)
  'outlook_send', 'outlook_reply', 'outlook_forward',
  'user_outlook_send', 'user_outlook_reply', 'user_outlook_forward',
  // Microsoft Teams (agent slot + user slot). The user_ twins are generated by
  // the full-parity loop in microsoft/tools-write.ts (every MS write tool gets
  // one); they send from the owner's personal Teams and so belong on this deny
  // surface. They were missing until the 2026-07-08 exhaustiveness check caught
  // the gap (the base sends were denied but the user_ twins were not, leaving the
  // Trainer/Healer able to post from the owner's Teams).
  'teams_send_message', 'teams_send_channel_message',
  'user_teams_send_message', 'user_teams_send_channel_message',
  // Twilio SMS
  'sms_send',
  // iMessage
  'imessage_send', 'imessage_list_contacts',
  // Twilio Voice
  'voice_call', 'voice_call_end', 'voice_call_status',
];

/**
 * NOT-APPLICABLE ledger for the SEND_TO_PEOPLE exhaustiveness check (anti-omission,
 * 2026-07-08). Every BASE tool in the registry must be either in SEND_TO_PEOPLE
 * (a comms-to-people deny) or matched here with a one-line reason. Keys are exact
 * tool names or family-prefix globs (trailing `*`); values are the reason a member
 * of that family is NOT comms-to-people on an owner channel. A new base tool that
 * matches neither fails the conformance test + release gate, naming the tool, so
 * the developer must make a deny-or-exempt decision at add time.
 *
 * DELIBERATE fail-closed asymmetry for the comms-bearing families (gmail_ /
 * outlook_ / teams_): those get NO blanket family glob, only exact entries for
 * their non-send members. So a NEW send in one of those families (e.g. a
 * gmail_send_scheduled) is unmatched here and FAILS, forcing a deny decision,
 * rather than being auto-swallowed by a broad `gmail_*` exemption. Clearly-
 * non-comms families use humane prefix globs.
 *
 * SCOPE: base names only. user_ twins are handled two ways, not here: user_ SEND
 * twins by USER_TWINNED_SEND_PREFIXES parity below, and user_ READ twins by the
 * Trainer's separate read-deny derived from the read-tool definition arrays
 * (techniques/trainer-agent.ts). file/link SHARING (share_file, share_publicly,
 * drive_share, calendar_respond_invite) is intentionally NOT comms-to-people: it
 * creates a shareable artifact / RSVP, not a free-form message on an owner comms
 * channel, matching the historical scope of this surface.
 */
export const SEND_TO_PEOPLE_NA: Readonly<Record<string, string>> = {
  // ── clearly non-comms families (humane prefix globs) ──
  'load_tool_docs': 'meta: loads a tool schema',
  'file_*': 'local filesystem, not a comms channel',
  'exec': 'local shell, not a comms channel',
  'screen_*': 'local screen capture/broadcast, not a person-to-person channel',
  'keyboard_*': 'local input synthesis',
  'mouse_*': 'local input synthesis',
  'applescript_run': 'local automation, not a comms channel',
  'scratchpad_*': 'in-turn scratch memory',
  'get_current_time': 'clock lookup',
  'convert_time': 'timezone math',
  'web_*': 'read-only web fetch/search, reaches no person',
  'canvas_*': 'right-dock view surface, not an owner comms channel',
  'open_browser': 'right-dock view surface',
  'image_create': 'media generator',
  'video_create': 'media generator',
  'music_create': 'media generator',
  'tts_create': 'media generator',
  'transcribe_audio': 'converts the owner\'s own audio input',
  'pdf_*': 'local document ops',
  'contact_*': 'DOJO contact store reads/writes (agent-authored), sends nothing',
  'contacts_*': 'Microsoft directory reads/writes, sends nothing',
  'credential_*': 'encrypted credential store',
  'vault_*': 'long-term memory store',
  'recall_*': 'conversation recall (own history)',
  'history_*': 'conversation history reads',
  'squad_*': 'agent-to-agent shared memory (not an owner channel)',
  'tracker_*': 'internal project bookkeeping',
  'reminder_create': 'internal reminder bookkeeping',
  'loop_resolve': 'retires a tracked open loop; internal bookkeeping, sends nothing',
  'list_agents': 'agent management',
  'list_groups': 'agent management',
  'list_models': 'agent management',
  'spawn_agent': 'agent management',
  'kill_agent': 'agent management',
  'spawn_timeout_decision': 'agent management',
  'get_agent_profile': 'agent management',
  'update_agent': 'agent management',
  'create_agent_group': 'agent management',
  'update_group': 'agent management',
  'assign_to_group': 'agent management',
  'delete_group': 'agent management',
  'get_group_detail': 'agent management',
  'send_to_agent': 'agent-to-agent message (explicitly kept, not an owner channel)',
  'broadcast_to_group': 'agent-to-agent broadcast (not an owner channel)',
  'complete_task': 'agent coordination bookkeeping',
  'reset_session': 'agent session management',
  'save_technique': 'technique authoring',
  'use_technique': 'technique execution',
  'technique_*': 'technique authoring/reads',
  'publish_technique': 'technique authoring',
  'update_technique': 'technique authoring',
  'submit_technique_for_review': 'technique authoring',
  'delete_technique': 'technique authoring',
  'list_techniques': 'technique listing',
  'show_to_user': 'in-dashboard reply to the owner (explicitly kept)',
  'share_publicly': 'creates a public share link, sends no message on a channel',
  'share_file': 'creates a file share, sends no message on a channel',
  'add_safe_sender': 'safe-sender admin',
  'set_user_presence': 'platform control',
  'open_settings': 'platform control',
  'dashboard_navigate': 'platform control',
  'set_capability_model': 'platform control',
  'set_voice': 'platform control',
  'set_channel': 'platform control',
  'check_for_update': 'platform control',
  'apply_update': 'platform control',
  'cost_summary': 'oversight read',
  'channel_inspect': 'oversight read',
  'dreamer_run_now': 'oversight trigger',
  'approve_destructive_action': 'oversight approval',
  'healer_*': 'self-repair bookkeeping',
  'tunnel': 'remote-access plumbing',
  'email_search': 'merged mailbox READ across accounts, sends nothing',
  'calendar_*': 'calendar reads/writes/RSVP (Google + _ms), not a free-form owner-channel message',
  'drive_*': 'Google Drive file ops (incl. drive_share, a file share not a message)',
  'docs_*': 'Google Docs ops',
  'sheets_*': 'Google Sheets ops',
  'tasks_*': 'Google Tasks ops',
  'slides_*': 'Google Slides ops',
  'forms_*': 'Google Forms ops',
  'onedrive_*': 'OneDrive file ops',
  'onenote_*': 'OneNote ops',
  'sharepoint_*': 'SharePoint reads',
  'online_meeting_*': 'meeting scheduling, not a message',
  'office_*': 'Office document ops',
  'plaud_*': 'voice-recorder integration reads',
  // ── comms-bearing families: EXACT non-send members only (fail-closed) ──
  'gmail_search': 'Gmail read', 'gmail_read': 'Gmail read', 'gmail_inbox': 'Gmail read',
  'gmail_label': 'Gmail label mgmt', 'gmail_list_labels': 'Gmail label mgmt',
  'gmail_create_label': 'Gmail label mgmt', 'gmail_delete_label': 'Gmail label mgmt',
  'gmail_list_attachments': 'Gmail attachment read', 'gmail_read_attachment': 'Gmail attachment read',
  'outlook_search': 'Outlook read', 'outlook_read': 'Outlook read', 'outlook_inbox': 'Outlook read',
  'outlook_mark_read': 'Outlook state', 'outlook_delete': 'Outlook mailbox op',
  'outlook_move_to_folder': 'Outlook folder op', 'outlook_list_folders': 'Outlook folder read',
  'outlook_create_folder': 'Outlook folder op', 'outlook_categories_set': 'Outlook category op',
  'outlook_list_attachments': 'Outlook attachment read', 'outlook_download_attachment': 'Outlook attachment read',
  'teams_read_messages': 'Teams read', 'teams_list_teams': 'Teams read', 'teams_list_channels': 'Teams read',
  'teams_read_channel_messages': 'Teams read', 'teams_list_chats': 'Teams read',
  'teams_create_chat': 'Teams chat creation (no message body sent)',
  'teams_list_attachments': 'Teams attachment read', 'teams_download_attachment': 'Teams attachment read',
};

/**
 * Base comms-send families that generate owner-account (user_) twins: the Google
 * + Microsoft channels (email + Teams). Twilio SMS/Voice and Apple iMessage have
 * NO user-slot twin. Mirrors the twin-generation rule (every Google/Microsoft
 * write tool gets a user_ variant, see google/tools-write.ts +
 * microsoft/tools-write.ts). The conformance check requires: for every base send
 * denied in SEND_TO_PEOPLE whose name starts with one of these prefixes, its
 * user_<name> twin is ALSO denied, or the Trainer/Healer under-block the owner's
 * personal account. A new twinned send family added here + its base sends above
 * is the only edit a future channel needs; the base full-registry accounting is
 * what forces that edit.
 */
export const USER_TWINNED_SEND_PREFIXES: readonly string[] = ['gmail_', 'outlook_', 'teams_'];

/**
 * The owner's identity + platform-config files. ONE static prefix set, consumed
 * TWO ways:
 *  - a HARD file_write deny for the Trainer (permissions.ts checkPermission),
 *    which now holds broad file_write '*' for technique work but must never
 *    touch the owner's profile/config; and
 *  - a destructive-classify signal for the Healer (destructive-gate.ts), whose
 *    full primary-equivalent write grant makes a write here a new destructive
 *    path that routes through the approval hold rather than a free write.
 *
 * SOUL.md, every *-SOUL.md, and secrets.yaml are ALREADY covered by
 * permissions.ts GLOBAL_FILE_WRITE_DENY (writes) and GLOBAL_EXEC_DENY_SUBSTRINGS
 * (shell), so they need no entry here. Patterns are matched by
 * isProtectedIdentityPath (permissions.ts) against the canonicalized,
 * '..'-collapsed target, so a traversal cannot slip the prefix match.
 *
 * Glob semantics (permissions.ts matchGlob): `*` matches within one path
 * segment, `**` crosses segments. `~/.dojo/*.yaml` therefore covers the loose
 * config yamls directly under ~/.dojo (secrets.yaml matches too, harmless: it is
 * already globally denied), while nested config lives under `~/.dojo/config/**`.
 */
export const PROTECTED_IDENTITY_PATHS: readonly string[] = [
  '~/.dojo/prompts/USER.md',
  '~/.dojo/config/**',
  '~/.dojo/*.yaml',
];
