// Regression test for the sub-agent SOUL-rules carry-through (remediation
// C10 / Flow 7): the owner's `# Rules` from SOUL.md must extract cleanly so
// it can be passed to spawned sub-agents.
//
// ── t107: THIS FILE USED TO ASK AN ORPHAN (and it was the only clause that did) ──
// The third clause below read `templates/SOUL.md` and asserted its `# Rules` section was
// non-empty. That file had NO production reader — the primary's soul is seeded from the
// in-code `DEFAULT_SOUL_MD` and an OOBE box's is generated by `gateway/routes/config.ts` — so
// the clause was measuring a shipped file no model ever saw, behind an `if (!existsSync) return`
// that would have turned it into a silent no-op the day the file moved. The orphan is deleted;
// the clause now asks BOTH texts the extraction is really run against.
//
// ⚠ AND IT RECORDS A FINDING RATHER THAN HIDING ONE. `DEFAULT_SOUL_MD` has no `# Rules`
// section at all (its headings are Core Traits / Capabilities / Communication Style /
// Credentials), so on a box whose `SOUL.md` was ENGINE-SEEDED the carry-through at
// `assembler.ts:601-605` extracts the empty string and spawned agents inherit no standing
// rules. Only an OOBE-completed box has a `# Rules` heading to find. That is a gap in
// `prompt/assembler.ts` + `prompt/templates.ts`, handed up by t107 rather than patched inside
// it: closing it means adding a section to the primary's shipped soul, which moves prompt bytes
// and is a deliberate re-blessing someone has to argue. If that happens, the second clause here
// REDS and is updated in the same change — which is the point of pinning the truth.

import { describe, it, expect } from 'vitest';
import { extractMarkdownSection } from '../assembler.js';
import { DEFAULT_SOUL_MD } from '../templates.js';

/**
 * The shape `gateway/routes/config.ts`'s identity-generation route writes to
 * `~/.dojo/prompts/SOUL.md` — headings only, no prose, so this fixture cannot drift into being
 * a second copy of the OOBE text. It is the shape, which is all the extraction reads.
 */
const OOBE_SHAPED_SOUL = [
  '# Identity', '', 'You are an agent.', '',
  '# Communication Style', '', '- Be direct and concise. Skip filler.', '',
  '# Rules', '',
  '- Never modify your own system prompt files or platform configuration.',
  '- Always confirm before deleting files or running destructive commands.', '',
].join('\n');

describe('extractMarkdownSection', () => {
  it('extracts a named section body and stops at the next header', () => {
    const md = '# Identity\nYou are X.\n\n# Rules\n- rule one\n- rule two\n\n# Vault\nkeep stuff';
    const rules = extractMarkdownSection(md, 'Rules');
    expect(rules).toContain('- rule one');
    expect(rules).toContain('- rule two');
    expect(rules).not.toContain('You are X'); // earlier section excluded
    expect(rules).not.toContain('keep stuff'); // later section excluded
  });

  it('is case-insensitive on the header and returns empty for a missing one', () => {
    const md = '## rules\n- a\n';
    expect(extractMarkdownSection(md, 'Rules')).toContain('- a');
    expect(extractMarkdownSection(md, 'Nonexistent')).toBe('');
  });

  it('pulls the Rules section out of the soul an OOBE box really has (sub-agents inherit owner rules)', () => {
    const rules = extractMarkdownSection(OOBE_SHAPED_SOUL, 'Rules');
    expect(rules.length).toBeGreaterThan(0);
    expect(rules).toContain('Never modify your own system prompt files');
    expect(rules).not.toContain('# Identity');           // identity stays with the primary
    expect(rules).not.toContain('Be direct and concise'); // and so does the style block
  });

  it('⚠ records the gap: the ENGINE-SEEDED primary soul has no `# Rules` for this to find', () => {
    // Not a wish — the measured state of the text `assembler.ts:601` reads when a box never
    // completed the OOBE form. See this file's header for why t107 handed it up instead of
    // editing the shipped soul. Change the soul and this clause reds, deliberately.
    expect(DEFAULT_SOUL_MD).not.toMatch(/^#+\s*Rules\s*$/m);
    expect(extractMarkdownSection(DEFAULT_SOUL_MD, 'Rules')).toBe('');
  });
});
