// Regression test for the sub-agent SOUL-rules carry-through (remediation
// C10 / Flow 7): the owner's `# Rules` from SOUL.md must extract cleanly so
// it can be passed to spawned sub-agents.
//
// ── t107: THIS FILE USED TO ASK AN ORPHAN (and it was the only clause that did) ──
// The third clause below read `templates/SOUL.md` and asserted its `# Rules` section was
// non-empty. That file had NO production reader — the primary's soul is seeded from the
// in-code `DEFAULT_SOUL_MD` and an OOBE box's is generated by `gateway/routes/config.ts` — so
// the clause was measuring a shipped file no model ever saw, behind an `if (!existsSync) return`
// that would have turned it into a silent no-op the day the file moved. The orphan is deleted;
// the clause now asks BOTH texts the extraction is really run against.
//
// ── t111-A2: THE GAP THIS FILE RECORDED IS CLOSED, AND THE CLAUSE FLIPPED ──────────────
// t107 pinned a finding here rather than hiding one: `DEFAULT_SOUL_MD` had NO `Rules` section
// (its headings were Core Traits / Capabilities / Communication Style / Credentials), so on a
// box whose `SOUL.md` was ENGINE-SEEDED the carry-through at `assembler.ts:601-605` extracted
// the empty string and spawned agents inherited no standing rules — only an OOBE-completed box
// had a heading to find. t111 added `## Rules` to the shipped soul carrying the same four
// universal rules the OOBE route writes, which moves the primary's prompt bytes ONCE and is
// argued as a deliberate re-bless in that commit. The last clause below is therefore the
// INVERSE of what t107 wrote, by design: it now asserts the heading exists and the extraction
// returns those four rules. That is the pinning working as intended, not drift.

import { describe, it, expect } from 'vitest';
import { extractMarkdownSection } from '../assembler.js';
import { DEFAULT_SOUL_MD } from '../templates.js';

/**
 * The shape `gateway/routes/config.ts`'s identity-generation route writes to
 * `~/.dojo/prompts/SOUL.md` — headings only, no prose, so this fixture cannot drift into being
 * a second copy of the OOBE text. It is the shape, which is all the extraction reads.
 */
const OOBE_SHAPED_SOUL = [
  '# Identity', '', 'You are an agent.', '',
  '# Communication Style', '', '- Be direct and concise. Skip filler.', '',
  '# Rules', '',
  '- Never modify your own system prompt files or platform configuration.',
  '- Always confirm before deleting files or running destructive commands.', '',
].join('\n');

describe('extractMarkdownSection', () => {
  it('extracts a named section body and stops at the next header', () => {
    const md = '# Identity\nYou are X.\n\n# Rules\n- rule one\n- rule two\n\n# Vault\nkeep stuff';
    const rules = extractMarkdownSection(md, 'Rules');
    expect(rules).toContain('- rule one');
    expect(rules).toContain('- rule two');
    expect(rules).not.toContain('You are X'); // earlier section excluded
    expect(rules).not.toContain('keep stuff'); // later section excluded
  });

  it('is case-insensitive on the header and returns empty for a missing one', () => {
    const md = '## rules\n- a\n';
    expect(extractMarkdownSection(md, 'Rules')).toContain('- a');
    expect(extractMarkdownSection(md, 'Nonexistent')).toBe('');
  });

  it('pulls the Rules section out of the soul an OOBE box really has (sub-agents inherit owner rules)', () => {
    const rules = extractMarkdownSection(OOBE_SHAPED_SOUL, 'Rules');
    expect(rules.length).toBeGreaterThan(0);
    expect(rules).toContain('Never modify your own system prompt files');
    expect(rules).not.toContain('# Identity');           // identity stays with the primary
    expect(rules).not.toContain('Be direct and concise'); // and so does the style block
  });

  it('the ENGINE-SEEDED primary soul now carries the `Rules` the carry-through reads (t111-A2)', () => {
    // t107 pinned the GAP here: `DEFAULT_SOUL_MD` had no `Rules` heading, so the
    // `assembler.ts:601` carry-through extracted `''` and spawned agents on an engine-seeded
    // box inherited no standing rules. t111 closed it by adding the section, which is why this
    // clause is the inverse of what it said — the deliberate prefix move is argued in that
    // commit. Both directions: the heading EXISTS, and the extraction returns the four
    // universal rules by their own bytes, so deleting the section or re-levelling the heading
    // past `extractMarkdownSection`'s `#{1,3}` window reds here.
    expect(DEFAULT_SOUL_MD).toMatch(/^#{1,3}\s*Rules\s*$/m);
    const rules = extractMarkdownSection(DEFAULT_SOUL_MD, 'Rules');
    expect(rules).toContain('- Never modify your own system prompt files or platform configuration.');
    expect(rules).toContain('- Always confirm before deleting files or running destructive commands.');
    expect(rules).toContain('- If a task will take multiple steps, briefly outline the plan before starting.');
    expect(rules).toContain("- When you encounter an error, explain what went wrong and what you'll try next.");
    // and it is the RULES, not the whole soul: the neighbouring sections stay with the primary.
    expect(rules).not.toContain('Core Traits');
    expect(rules).not.toContain('Credentials');
    expect(rules).not.toContain('{{agent_name}}');
  });
});
