import { Hono } from 'hono';
import { v4 as uuidv4 } from 'uuid';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { getDb } from '../../db/connection.js';
import { getAgentRuntime } from '../../agent/runtime.js';
import { spawnAgent, terminateAgent } from '../../agent/spawner.js';
import { parseCreatedByKind } from '../../agent/created-by-kind.js';
import { stopAgent } from '../../agent/runtime.js';
import { getAgentMessages } from '../../agent/agent-bus.js';
import {
  insertMessageIfAbsent, rewriteSystemPromptRow, deleteAllForAgent, deleteAgentBusRowsFor,
} from '../../memory/message-store.js';
import { createLogger } from '../../logger.js';
import { broadcast } from '../ws.js';
import { isPrimaryAgent, getPrimaryAgentId, getHealerAgentId, getDreamerAgentId, getImaginerAgentId } from '../../config/platform.js';
import { sanitizeMessagesOnModelChange } from '../../agent/model-switch.js';
import type { AgentDetail, Model, Message, AgentMessage } from '@dojo/shared';
import { deriveOrigin, legacyOriginInputs, NEW_SESSION_DIVIDER} from '@dojo/shared';
import { noteRouteFailure } from './route-failure.js';
import { resolveChildScope } from '../../agent/scope.js';
import { getAgentPermissions } from '../../agent/permissions.js';

const logger = createLogger('agents-routes');
const agentsRouter = new Hono();

// GET / - list all agents with detail
agentsRouter.get('/', (c) => {
  const db = getDb();
  const rows = db.prepare('SELECT * FROM agents ORDER BY created_at ASC').all() as Array<Record<string, unknown>>;

  const agents: AgentDetail[] = rows.map(row => rowToAgentDetail(row));
  return c.json({ ok: true, data: agents });
});

// GET /:id - single agent detail
agentsRouter.get('/:id', (c) => {
  const id = c.req.param('id');
  const db = getDb();
  const row = db.prepare('SELECT * FROM agents WHERE id = ?').get(id) as Record<string, unknown> | undefined;

  if (!row) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  const agent = rowToAgentDetail(row);
  // ── THE EFFECTIVE SCOPE, READABLE ANY TIME (PHASE-5 T5 Step 2) ──
  // `permissions` is the STORED blob and it is not the answer to "what can this
  // agent actually do": it is `'{}'` for 40 of 56 agents on the dev body, it is
  // partial for others, and the platform's own identity rules override it for
  // the primary. `effectiveScope` is what `getAgentPermissions` actually returns
  // — defaults filled in, identity applied, the agent's own artifact directory
  // present — so nobody has to reconstruct it from three files to answer the
  // question. Additive: `permissions` still carries the stored blob byte for
  // byte, because a reader that wants to know what was WRITTEN still can.
  return c.json({ ok: true, data: { ...agent, effectiveScope: getAgentPermissions(id) } });
});

// PATCH /:id/model - set agent's model
agentsRouter.patch('/:id/model', async (c) => {
  const id = c.req.param('id');
  const db = getDb();

  const agent = db.prepare('SELECT id FROM agents WHERE id = ?').get(id);
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  const body = await c.req.json().catch(() => null);
  if (!body || typeof body.modelId !== 'string') {
    return c.json({ ok: false, error: 'modelId string is required' }, 400);
  }

  const { modelId } = body;

  if (modelId === 'auto') {
    db.prepare("UPDATE agents SET model_id = 'auto', updated_at = datetime('now') WHERE id = ?").run(id);
    logger.info('Agent model set to auto-router', { agentId: id });
  } else {
    const model = db.prepare('SELECT id, name FROM models WHERE id = ? AND is_enabled = 1').get(modelId) as { id: string; name: string } | undefined;
    if (!model) {
      return c.json({ ok: false, error: 'Model not found or not enabled' }, 400);
    }
    db.prepare("UPDATE agents SET model_id = ?, updated_at = datetime('now') WHERE id = ?").run(modelId, id);
    logger.info('Agent model updated', { agentId: id, modelId, modelName: model.name });
  }

  // Sanitize tool call messages so the new model doesn't choke on
  // tool_use IDs generated by the previous model
  sanitizeMessagesOnModelChange(id);

  // Keep config-table model keys in sync for persistent agents whose runtime
  // reads from config rather than agents.model_id directly.
  const upsert = db.prepare(`
    INSERT INTO config (key, value, updated_at) VALUES (?, ?, datetime('now'))
    ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
  `);
  if (id === getHealerAgentId()) {
    upsert.run('healer_model_id', modelId);
    logger.info('Synced healer_model_id config key', { modelId });
  } else if (id === getDreamerAgentId()) {
    upsert.run('dreaming_model_id', modelId);
    logger.info('Synced dreaming_model_id config key', { modelId });
  } else if (id === getImaginerAgentId()) {
    upsert.run('imaginer_image_model', modelId);
    logger.info('Synced imaginer_image_model config key', { modelId });
  }

  // Return updated agent
  const row = db.prepare('SELECT * FROM agents WHERE id = ?').get(id) as Record<string, unknown>;
  return c.json({ ok: true, data: rowToAgentDetail(row) });
});

// POST / — create standalone agent from dashboard
agentsRouter.post('/', async (c) => {
  const body = await c.req.json().catch(() => null);

  if (!body || typeof body.name !== 'string' || typeof body.systemPrompt !== 'string') {
    return c.json({ ok: false, error: 'name (string) and systemPrompt (string) are required' }, 400);
  }

  try {
    const db = getDb();
    const agentId = uuidv4();

    // ── THE SAME VALIDATION PATH THE SPAWNER USES (PHASE-5 T5 Step 2) ──
    // This route used to write `JSON.stringify(body.permissions ?? {})` straight
    // into the row: no schema, no bound, no reader. A manifest of the wrong shape
    // was stored happily and silently downgraded to the default by the next
    // reader, and a manifest claiming more than the platform grants was stored
    // just as happily. The plan's requirement is that dashboard agent creation
    // goes through the SAME path, so it does — literally the same function.
    //
    // The parent here is the PRIMARY agent's scope, because that is what a
    // dashboard-created agent is bounded by: the route is the owner acting, and
    // the owner's own agent is the ceiling. A body that names no manifest gets
    // the decided default, exactly as a spawn does.
    const scope = resolveChildScope(
      body.permissions,
      getAgentPermissions(getPrimaryAgentId()),
      agentId,
    );
    if (!scope.ok) {
      // A REFUSAL, NOT A DOWNGRADE. 400 rather than 500: the caller sent
      // something the platform will not store, and the message names the field.
      logger.warn('Dashboard agent creation refused an invalid manifest', { reason: scope.reason });
      return c.json({ ok: false, error: `Agent not created — ${scope.reason}` }, 400);
    }

    const resolvedModelId = body.modelId || null;
    const config = JSON.stringify({
      shareUserProfile: body.shareUserProfile || undefined,
    });
    const timeoutSeconds = body.timeout ? Number(body.timeout) : null;
    const timeoutAt = timeoutSeconds ? new Date(Date.now() + timeoutSeconds * 1000).toISOString() : null;

    const classification = body.classification === 'ronin' ? 'ronin' : 'apprentice';

    const groupId = body.groupId ?? null;

    // T11 Step 1b: who made this agent. This route is the dashboard create form, so a
    // person made it — unless the caller DECLARES otherwise, which is how the behavioral
    // harness stamps its BehaviorBot and its five fixture peers as disposable. An
    // unrecognised value falls back to 'user' (parseCreatedByKind returns null), so a
    // typo can only ever NARROW what a sweep may touch, never widen it.
    const createdByKind = parseCreatedByKind(body.createdByKind) ?? 'user';

    db.prepare(`
      INSERT INTO agents (id, name, model_id, system_prompt_path, status, config, created_by, created_by_kind,
                          parent_agent, spawn_depth, agent_type, classification, group_id, max_runtime, timeout_at,
                          permissions, tools_policy, equipped_techniques, task_id, created_at, updated_at)
      VALUES (?, ?, ?, NULL, 'idle', ?, 'dashboard', ?,
              NULL, 0, 'standard', ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
    `).run(
      agentId,
      body.name,
      resolvedModelId,
      config,
      createdByKind,
      classification,
      groupId,
      timeoutSeconds,
      timeoutAt,
      JSON.stringify(scope.manifest),
      JSON.stringify(body.toolsPolicy ?? {}),
      JSON.stringify(body.equippedTechniques ?? []),
      body.taskId ?? null,
    );

    // Store system prompt as first message (no spawn injection)
    insertMessageIfAbsent({ id: uuidv4(), agentId, role: 'system', content: body.systemPrompt });

    // FA-PT6: persist the charter durably (migration 096) so getSoulContent
    // reads it directly instead of sniffing the earliest role='system' row.
    try {
      db.prepare('UPDATE agents SET charter = ? WHERE id = ?').run(body.systemPrompt, agentId);
    } catch { /* charter column may not exist on a very old database */ }

    // Store initial user message — just the task, no IMPORTANT INSTRUCTIONS
    const initMsgId = uuidv4();
    insertMessageIfAbsent({ id: initMsgId, agentId, role: 'user', content: body.systemPrompt });
    // T9 (research 17 D4): persisted and never broadcast. It is an owner-lane user row
    // that the chat history route serves, so the agent's first message used to appear
    // only on reload. The agent:created event below tells the dashboard the agent exists;
    // it says nothing about this row.
    broadcast({
      type: 'chat:message',
      agentId,
      message: {
        id: initMsgId, agentId, role: 'user' as const, content: body.systemPrompt,
        tokenCount: null, modelId: null, cost: null, latencyMs: null,
        createdAt: new Date().toISOString(),
      },
    });

    // Start the agent runtime
    const runtime = getAgentRuntime();
    runtime.handleMessage(agentId, body.systemPrompt).catch(err => {
      logger.error('Dashboard agent initial run failed', {
        agentId,
        error: err instanceof Error ? err.message : String(err),
      });
    });

    logger.info('Dashboard agent created', { agentId, name: body.name });

    broadcast({
      type: 'agent:created',
      data: {
        id: agentId,
        name: body.name,
        modelId: resolvedModelId,
        systemPromptPath: null,
        status: 'idle' as const,
        config: JSON.parse(config),
        createdBy: 'dashboard',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        parentAgent: null,
        spawnDepth: 0,
        agentType: 'standard' as const,
        classification: classification as 'ronin' | 'apprentice',
        groupId: null,
        maxRuntime: timeoutSeconds,
        timeoutAt,
        permissions: scope.manifest,
        toolsPolicy: body.toolsPolicy ?? {},
        equippedTechniques: body.equippedTechniques ?? [],
        taskId: body.taskId ?? null,
      },
    });

    const row = db.prepare('SELECT * FROM agents WHERE id = ?').get(agentId) as Record<string, unknown>;
    return c.json({ ok: true, data: rowToAgentDetail(row) }, 201);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error('Failed to create agent', { error: msg });
    return c.json({ ok: false, error: msg }, 500);
  }
});

// GET /:id/system-prompt — get agent's system prompt
agentsRouter.get('/:id/system-prompt', (c) => {
  const id = c.req.param('id');
  const db = getDb();

  if (isPrimaryAgent(id)) {
    const soulPath = path.join(os.homedir(), '.dojo', 'prompts', 'SOUL.md');
    try {
      const content = fs.readFileSync(soulPath, 'utf-8');
      return c.json({ ok: true, data: { content } });
    } catch (err) {
      noteRouteFailure(c, logger, err);
      return c.json({ ok: true, data: { content: '' } });
    }
  }

  const msg = db.prepare("SELECT content FROM messages WHERE agent_id = ? AND role = 'system' ORDER BY rowid ASC LIMIT 1").get(id) as { content: string } | undefined;
  return c.json({ ok: true, data: { content: msg?.content ?? '' } });
});

// PUT /:id — update agent config (model, system prompt, permissions, tools policy)
agentsRouter.put('/:id', async (c) => {
  const id = c.req.param('id');
  const db = getDb();

  const agent = db.prepare('SELECT id FROM agents WHERE id = ?').get(id);
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  const body = await c.req.json().catch(() => null);
  if (!body) {
    return c.json({ ok: false, error: 'Request body required' }, 400);
  }

  const updates: string[] = [];
  const params: unknown[] = [];

  if (typeof body.name === 'string' && body.name.trim()) {
    updates.push('name = ?');
    params.push(body.name.trim());
  }

  if (typeof body.modelId === 'string') {
    if (body.modelId === 'auto') {
      updates.push("model_id = 'auto'");
    } else {
      const model = db.prepare('SELECT id FROM models WHERE id = ? AND is_enabled = 1').get(body.modelId);
      if (!model) {
        return c.json({ ok: false, error: 'Model not found or not enabled' }, 400);
      }
      updates.push('model_id = ?');
      params.push(body.modelId);
    }
  }

  if (typeof body.systemPrompt === 'string') {
    // For primary agent, write to SOUL.md. For others, store as first system message.
    if (isPrimaryAgent(id)) {
      const soulPath = path.join(os.homedir(), '.dojo', 'prompts', 'SOUL.md');
      fs.mkdirSync(path.dirname(soulPath), { recursive: true });
      fs.writeFileSync(soulPath, body.systemPrompt, 'utf-8');
      logger.info('Primary agent SOUL.md updated via agent config', { agentId: id });
    } else {
      // Update or insert the system message for this agent
      const existing = db.prepare("SELECT id FROM messages WHERE agent_id = ? AND role = 'system' ORDER BY rowid ASC LIMIT 1").get(id) as { id: string } | undefined;
      if (existing) {
        rewriteSystemPromptRow(existing.id, body.systemPrompt);
      } else {
        insertMessageIfAbsent({ id: uuidv4(), agentId: id, role: 'system', content: body.systemPrompt });
      }
      // FA-PT6: keep the durable charter column (migration 096) in sync with the
      // edited system prompt, so getSoulContent reflects the update immediately.
      try {
        db.prepare('UPDATE agents SET charter = ? WHERE id = ?').run(body.systemPrompt, id);
      } catch { /* charter column may not exist on a very old database */ }
    }
  }

  if (body.permissions !== undefined) {
    updates.push('permissions = ?');
    params.push(JSON.stringify(body.permissions));
  }

  if (body.classification !== undefined && ['ronin', 'apprentice'].includes(body.classification)) {
    updates.push('classification = ?');
    params.push(body.classification);
  }

  if (body.config !== undefined && typeof body.config === 'object') {
    // Merge with existing config
    const existingCfg = db.prepare('SELECT config FROM agents WHERE id = ?').get(id) as { config: string } | undefined;
    const merged = { ...JSON.parse(existingCfg?.config || '{}'), ...body.config };
    updates.push('config = ?');
    params.push(JSON.stringify(merged));
  }

  if (body.toolsPolicy !== undefined) {
    updates.push('tools_policy = ?');
    params.push(JSON.stringify(body.toolsPolicy));
  }

  if (body.equippedTechniques !== undefined) {
    updates.push('equipped_techniques = ?');
    params.push(JSON.stringify(body.equippedTechniques));
  }

  if (body.dreamerIgnore !== undefined) {
    // Boolean toggle. When true, the agent's conversations are skipped
    // by the vault archive layer entirely — Dreamer never sees them.
    updates.push('dreamer_ignore = ?');
    params.push(body.dreamerIgnore ? 1 : 0);
  }

  // T11 Step 1b: who created this agent (migration 134), settable here for the same reason
  // permissions are — the behavioral harness RECONCILES its long-lived BehaviorBot on every
  // run rather than recreating it, so a bot that predates the column has no other way to
  // record what it has always been. WRITE-ONCE: an agent that already carries a kind keeps
  // it, so this can adopt an unstamped row and can never relabel a person's agent as
  // disposable. An unrecognised value is ignored (parseCreatedByKind returns null), leaving
  // the column NULL, which every sweep treats as "not mine".
  if (body.createdByKind !== undefined) {
    const kind = parseCreatedByKind(body.createdByKind);
    const already = db.prepare('SELECT created_by_kind FROM agents WHERE id = ?').get(id) as
      { created_by_kind: string | null } | undefined;
    if (kind && !already?.created_by_kind) {
      updates.push('created_by_kind = ?');
      params.push(kind);
    }
  }

  if (updates.length > 0) {
    updates.push("updated_at = datetime('now')");
    params.push(id);
    db.prepare(`UPDATE agents SET ${updates.join(', ')} WHERE id = ?`).run(...params);
  }

  logger.info('Agent config updated', { agentId: id, fields: Object.keys(body) });

  const row = db.prepare('SELECT * FROM agents WHERE id = ?').get(id) as Record<string, unknown>;
  return c.json({ ok: true, data: rowToAgentDetail(row) });
});

// DELETE /:id — terminate agent (cascade)
agentsRouter.delete('/:id', (c) => {
  const id = c.req.param('id');
  const db = getDb();

  const agent = db.prepare('SELECT id, status, classification FROM agents WHERE id = ?').get(id) as { id: string; status: string; classification: string } | undefined;
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  if (agent.classification === 'sensei') {
    return c.json({ ok: false, error: 'Cannot terminate a sensei agent' }, 403);
  }

  if (agent.status === 'terminated') {
    return c.json({ ok: false, error: 'Agent is already terminated' }, 400);
  }

  terminateAgent(id, 'Terminated via dashboard');
  return c.json({ ok: true, data: { agentId: id, status: 'terminated' } });
});

// POST /:id/stop — halt a working agent and set to idle
agentsRouter.post('/:id/stop', (c) => {
  const id = c.req.param('id');
  const db = getDb();

  const agent = db.prepare('SELECT id, status FROM agents WHERE id = ?').get(id) as { id: string; status: string } | undefined;
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  if (agent.status !== 'working') {
    return c.json({ ok: false, error: 'Agent is not currently working' }, 400);
  }

  stopAgent(id);

  // Also set to idle immediately in the DB so the UI updates right away
  // (the runtime loop will also set it when it catches the stop flag)
  db.prepare("UPDATE agents SET status = 'idle', updated_at = datetime('now') WHERE id = ?").run(id);
  broadcast({ type: 'agent:status', agentId: id, status: 'idle' });

  logger.info('Agent stopped via dashboard', { agentId: id });
  return c.json({ ok: true, data: { agentId: id, status: 'idle' } });
});

// POST /:id/reset-session — reset a single agent's session.
// v2.3.19 (finding #196): pre-spec, dev-test-tools/bin/reset only set
// session_started_at via raw SQL, skipping the divider, broadcast,
// archive-to-vault, and reorientation prompt that the agent's
// reset_session tool does. That made dev resets invisible in the chat
// and structurally different from real resets. This endpoint mirrors
// the tool exactly, so dev tooling AND any future UI button get the
// real behavior.
agentsRouter.post('/:id/reset-session', async (c) => {
  const id = c.req.param('id');
  const db = getDb();
  const agent = db.prepare('SELECT id, name, status FROM agents WHERE id = ?')
    .get(id) as { id: string; name: string; status: string } | undefined;
  if (!agent) return c.json({ ok: false, error: 'Agent not found' }, 404);
  if (agent.status === 'terminated') {
    return c.json({ ok: false, error: 'Agent is terminated — no live session to reset' }, 400);
  }

  try {
    // 1. Archive current conversation to vault (best-effort).
    const { archiveAgentConversation } = await import('../../vault/archive.js');
    try { archiveAgentConversation(id, true); } catch { /* */ }

    // 1b. Clear any stale runtime signals so the post-reset agent starts
    //     truly clean. Without this, a previously-stopped agent stays
    //     "stopped" — the next user message hits the v2 loop's stop check,
    //     the flag clears, but the loop bails immediately without
    //     processing the user message. Same risk for queued wakeups and
    //     preempt flags. (2026-06-02 bug fix.)
    try {
      const { stoppedAgents, preemptedAgents, pendingWakeups } = await import('../../agent/shared-state.js');
      stoppedAgents.delete(id);
      preemptedAgents.delete(id);
      pendingWakeups.delete(id);
    } catch { /* best-effort */ }

    // 2. Set session boundary + clear continuity brief + clear scratchpad.
    //    (Scratchpad is session-scoped: the outline an agent built for the
    //    prior task isn't relevant once the session resets.)
    const boundary = new Date().toISOString().replace('T', ' ').replace(/\.\d+Z$/, '');
    db.prepare(
      "UPDATE agents SET session_started_at = ?, updated_at = ?, " +
      "config = json_remove(COALESCE(config, '{}'), '$.continuityBrief', '$.scratchpad') WHERE id = ?",
    ).run(boundary, boundary, id);
    // Carry a fired-but-undelivered reminder/scheduler event across the reset
    // boundary so it survives (engine-event queries gate created_at >=
    // session_started_at). Unclaimed deliverable engine rows only.
    try {
      const { rehomeUnclaimedEngineEvents } = await import('../../agent/v2/counterparty.js');
      rehomeUnclaimedEngineEvents(id, boundary);
    } catch { /* best-effort carry-over, never block the reset */ }
    // Clear per-conversation served tracking on reset (turn-continuity state).
    try {
      const { clearServedConversations } = await import('../../agent/turn-state.js');
      clearServedConversations(id);
    } catch { /* ignore */ }

    // 3. Insert UI divider + broadcast.
    const dividerId = uuidv4();
    // The divider's created_at is stamped by the writer at insert time rather than
    // pinned to `boundary` (computed a few lines up). Every session query is
    // `created_at >= session_started_at`, so at-or-after the boundary keeps the row
    // inside the new session; the broadcast still quotes `boundary` for the UI.
    insertMessageIfAbsent({ id: dividerId, agentId: id, role: 'system', content: NEW_SESSION_DIVIDER });
    broadcast({
      type: 'chat:message',
      agentId: id,
      message: {
        id: dividerId, agentId: id, role: 'system', content: NEW_SESSION_DIVIDER,
        tokenCount: null, modelId: null, cost: null, latencyMs: null,
        createdAt: boundary,
      },
    });

    // 4. Insert reorientation prompt + broadcast.
    const { buildSessionResetMessage } = await import('../../agent/session-reset.js');
    const reorientId = uuidv4();
    const reorientContent = buildSessionResetMessage(id);
    insertMessageIfAbsent({ id: reorientId, agentId: id, role: 'system', content: reorientContent });
    broadcast({
      type: 'chat:message',
      agentId: id,
      message: {
        id: reorientId, agentId: id, role: 'system', content: reorientContent,
        tokenCount: null, modelId: null, cost: null, latencyMs: null,
        createdAt: boundary,
      },
    });

    // 5. Heal error/paused status. A reset clears the corrupted context
    // that's often the root cause.
    if (agent.status === 'error' || agent.status === 'paused') {
      db.prepare(
        "UPDATE agents SET status = 'idle', last_error = NULL, last_error_at = NULL, updated_at = datetime('now') WHERE id = ?",
      ).run(id);
      broadcast({ type: 'agent:status', agentId: id, status: 'idle' });
    }

    logger.info('Agent session reset via API', { agentId: id, agentName: agent.name });
    return c.json({ ok: true, data: { agentId: id, name: agent.name, boundary } });
  } catch (err) {
    logger.error('Failed to reset agent session', {
      agentId: id, error: err instanceof Error ? err.message : String(err),
    });
    return c.json({ ok: false, error: err instanceof Error ? err.message : 'Reset failed' }, 500);
  }
});

// POST /:id/purge — permanently delete a terminated agent and all its data
agentsRouter.post('/:id/purge', (c) => {
  const id = c.req.param('id');
  const db = getDb();

  // Prevent deleting primary agent
  if (isPrimaryAgent(id)) {
    return c.json({ ok: false, error: 'Cannot delete the primary agent' }, 400);
  }

  const agent = db.prepare('SELECT id, status FROM agents WHERE id = ?').get(id) as { id: string; status: string } | undefined;
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  if (agent.status !== 'terminated') {
    return c.json({ ok: false, error: 'Agent must be terminated before it can be deleted' }, 400);
  }

  // Delete all associated data
  deleteAllForAgent(id);
  // T4: the agent bus folded into `messages`, so its cascade is a scoped delete on the
  // same table rather than a second one. Both directions, exactly as before — the rows
  // this agent RECEIVED go with the line above; this catches the ones it SENT, which
  // live on the recipient's row.
  deleteAgentBusRowsFor(id);
  db.prepare('DELETE FROM summary_messages WHERE summary_id IN (SELECT id FROM summaries WHERE agent_id = ?)').run(id);
  db.prepare('DELETE FROM summary_parents WHERE summary_id IN (SELECT id FROM summaries WHERE agent_id = ?) OR parent_id IN (SELECT id FROM summaries WHERE agent_id = ?)').run(id, id);
  db.prepare('DELETE FROM summaries WHERE agent_id = ?').run(id);
  db.prepare('DELETE FROM context_items WHERE agent_id = ?').run(id);
  db.prepare('DELETE FROM large_files WHERE agent_id = ?').run(id);
  db.prepare('DELETE FROM audit_log WHERE agent_id = ?').run(id);
  db.prepare('DELETE FROM agents WHERE id = ?').run(id);

  logger.info('Agent permanently deleted', { agentId: id });
  return c.json({ ok: true, data: { agentId: id, deleted: true } });
});

// POST /:id/message — send direct message to agent
agentsRouter.post('/:id/message', async (c) => {
  const id = c.req.param('id');
  const body = await c.req.json().catch(() => null);

  if (!body || typeof body.content !== 'string' || body.content.trim().length === 0) {
    return c.json({ ok: false, error: 'content (string) is required' }, 400);
  }

  const db = getDb();
  const agent = db.prepare('SELECT id, status FROM agents WHERE id = ?').get(id) as { id: string; status: string } | undefined;
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  if (agent.status === 'terminated') {
    return c.json({ ok: false, error: 'Agent is terminated' }, 400);
  }

  if (agent.status === 'working') {
    return c.json({ ok: false, error: 'Agent is currently busy' }, 409);
  }

  const { content } = body;
  const messageId = uuidv4();

  // Persist as user message
  insertMessageIfAbsent({ id: messageId, agentId: id, role: 'user', content });
  // T9 (research 17 D4): persisted and never broadcast. The dashboard's own send route
  // (gateway/routes/chat.ts) broadcasts its user row; this one — the API path other
  // callers use to talk to an agent — did not, so an operator watching the chat saw the
  // agent start working on a message that was not on screen until they reloaded.
  broadcast({
    type: 'chat:message',
    agentId: id,
    message: {
      id: messageId, agentId: id, role: 'user' as const, content,
      tokenCount: null, modelId: null, cost: null, latencyMs: null,
      createdAt: new Date().toISOString(),
    },
  });

  // Trigger the agent runtime
  const runtime = getAgentRuntime();
  runtime.handleMessage(id, content).catch(err => {
    logger.error('Agent message handling failed', {
      agentId: id,
      error: err instanceof Error ? err.message : String(err),
    });
  });

  return c.json({ ok: true, data: { messageId, agentId: id } });
});

// GET /:id/messages — conversation history for this agent
agentsRouter.get('/:id/messages', (c) => {
  const id = c.req.param('id');
  const db = getDb();

  const agent = db.prepare('SELECT id FROM agents WHERE id = ?').get(id);
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  const limit = parseInt(c.req.query('limit') ?? '100', 10);
  const offset = parseInt(c.req.query('offset') ?? '0', 10);

  // Two predicates, two different questions (T6). `lane = 'owner'` is WHOSE traffic
  // this is — the fail-closed replacement for the physical table split, which is what
  // keeps this dashboard projection human-only now that peer A2A and engine rows live
  // in the same table. `retired_at IS NULL` is DISPLAY SUPPRESSION ONLY (research
  // 07 §2g): migration 102 stamped the legacy pre-cutover inter-agent rows so they
  // never surface again. It was covering for the lane while the split was physical;
  // it is not doing that job any more.
  const rows = db.prepare(`
    SELECT *, datetime(created_at/1000,'unixepoch') AS created_at FROM messages WHERE agent_id = ? AND retired_at IS NULL AND lane = 'owner'
    ORDER BY created_at ASC
    LIMIT ? OFFSET ?
  `).all(id, limit, offset) as Array<Record<string, unknown>>;

  const messages: Message[] = rows.map(row => ({
    id: row.id as string,
    agentId: row.agent_id as string,
    role: row.role as Message['role'],
    content: row.content as string,
    tokenCount: row.token_count as number | null,
    modelId: row.model_id as string | null,
    cost: row.cost as number | null,
    latencyMs: row.latency_ms as number | null,
    createdAt: row.created_at as string,
    // Carried so the dashboard can hide A2A-turn output and badge voice messages on
    // reload, not just on the live broadcast path. PROJECTED from the stamped lane and
    // channel — Sweep E re-points the dashboard onto those and deletes this field.
    source: row.lane === 'a2a' ? 'a2a' : row.channel === 'voice' ? 'voice' : null,
    // Canonical attribution for the dashboard's origin-based classifier. Same
    // projection the memory store applies; structured columns win, legacy rows
    // resolve via the marker shim inside deriveOrigin.
    origin: deriveOrigin({
      role: row.role as Message['role'],
      content: (row.content as string | null) ?? null,
      ...legacyOriginInputs(row.lane as string | null, row.channel as string | null),
      sourceAgentId: (row.source_agent_id as string | null) ?? null,
      a2aThreadId: (row.a2a_thread_id as string | null) ?? null,
      a2aIntent: (row.a2a_intent as string | null) ?? null,
      a2aRequiresResponse: (row.a2a_requires_response as number | null) ?? null,
      inboundMeta: (row.inbound_meta as string | null) ?? null,
      originIntent: (row.origin_intent as string | null) ?? null,
    }),
  }));

  return c.json({ ok: true, data: messages });
});

// GET /:id/agent-messages — inter-agent messages
agentsRouter.get('/:id/agent-messages', (c) => {
  const id = c.req.param('id');
  const db = getDb();

  const agent = db.prepare('SELECT id FROM agents WHERE id = ?').get(id);
  if (!agent) {
    return c.json({ ok: false, error: 'Agent not found' }, 404);
  }

  const direction = (c.req.query('direction') ?? 'both') as 'sent' | 'received' | 'both';
  const limit = parseInt(c.req.query('limit') ?? '50', 10);

  const messages: AgentMessage[] = getAgentMessages(id, { direction, limit });
  return c.json({ ok: true, data: messages });
});

function rowToAgentDetail(row: Record<string, unknown>): AgentDetail {
  const db = getDb();
  const agentId = row.id as string;
  let modelId = row.model_id as string | null;

  // Imaginer has no "brain" model — the agent card should show the image
  // generation model, which is stored in the config table, not agents.model_id.
  if (agentId === getImaginerAgentId()) {
    const cfgRow = db.prepare("SELECT value FROM config WHERE key = 'imaginer_image_model'").get() as { value: string } | undefined;
    if (cfgRow?.value) modelId = cfgRow.value;
  }

  // Get message count
  const msgCount = (db.prepare('SELECT COUNT(*) as count FROM messages WHERE agent_id = ?').get(agentId) as { count: number }).count;

  // Get model if set
  let model: Model | null = null;
  if (modelId) {
    const modelRow = db.prepare('SELECT * FROM models WHERE id = ?').get(modelId) as Record<string, unknown> | undefined;
    if (modelRow) {
      model = {
        id: modelRow.id as string,
        providerId: modelRow.provider_id as string,
        name: modelRow.name as string,
        apiModelId: modelRow.api_model_id as string,
        capabilities: JSON.parse(modelRow.capabilities as string),
        contextWindow: modelRow.context_window as number | null,
        maxOutputTokens: modelRow.max_output_tokens as number | null,
        inputCostPerM: modelRow.input_cost_per_m as number | null,
        outputCostPerM: modelRow.output_cost_per_m as number | null,
        isEnabled: Boolean(modelRow.is_enabled),
        thinkingEnabled: modelRow.thinking_enabled === null || modelRow.thinking_enabled === undefined
          ? true
          : Boolean(modelRow.thinking_enabled),
        numCtxOverride: typeof modelRow.num_ctx_override === 'number'
          ? modelRow.num_ctx_override
          : null,
        numCtxRecommended: typeof modelRow.num_ctx_recommended === 'number'
          ? modelRow.num_ctx_recommended
          : null,
        pricingUnit: (modelRow.pricing_unit === 'megapixel' || modelRow.pricing_unit === 'second' ||
                      modelRow.pricing_unit === 'character' || modelRow.pricing_unit === 'minute')
          ? modelRow.pricing_unit as 'megapixel' | 'second' | 'character' | 'minute'
          : 'token',
        costPerUnit: typeof modelRow.cost_per_unit === 'number'
          ? modelRow.cost_per_unit
          : (modelRow.pricing_unit === 'megapixel' && typeof modelRow.cost_per_megapixel === 'number'
            ? modelRow.cost_per_megapixel
            : null),
        costPerMegapixel: modelRow.pricing_unit === 'megapixel' && typeof modelRow.cost_per_megapixel === 'number'
          ? modelRow.cost_per_megapixel
          : null,
        // priceUnknown (derived, no column): the applicable rate is NULL rather
        // than an explicit 0. Token rows check input/output $/M; recognized
        // non-token rows check cost_per_unit (with the megapixel legacy
        // fallback). Per D-H an unknown rate bills as $0, so this keeps the
        // "price unknown" state visible instead of silently hidden.
        priceUnknown: (modelRow.pricing_unit === 'megapixel' || modelRow.pricing_unit === 'second' ||
                       modelRow.pricing_unit === 'character' || modelRow.pricing_unit === 'minute')
          ? !(typeof modelRow.cost_per_unit === 'number' ||
              (modelRow.pricing_unit === 'megapixel' && typeof modelRow.cost_per_megapixel === 'number'))
          : (modelRow.input_cost_per_m === null || modelRow.input_cost_per_m === undefined ||
             modelRow.output_cost_per_m === null || modelRow.output_cost_per_m === undefined),
        generationParams: (() => {
          if (typeof modelRow.generation_params !== 'string' || !modelRow.generation_params) return null;
          try { return JSON.parse(modelRow.generation_params) as Model['generationParams']; }
          catch { return null; }
        })(),
        voiceCatalog: (() => {
          if (typeof modelRow.voice_catalog !== 'string' || !modelRow.voice_catalog) return null;
          try {
            const parsed = JSON.parse(modelRow.voice_catalog);
            return Array.isArray(parsed) ? (parsed as Model['voiceCatalog']) : null;
          } catch { return null; }
        })(),
        createdAt: modelRow.created_at as string,
        updatedAt: modelRow.updated_at as string,
      };
    }
  }

  // Get uptime from runtime
  const runtime = getAgentRuntime();
  const uptime = runtime.getAgentUptime(agentId);

  return {
    id: agentId,
    name: row.name as string,
    modelId: modelId,
    systemPromptPath: row.system_prompt_path as string | null,
    status: row.status as AgentDetail['status'],
    config: JSON.parse((row.config as string) || '{}'),
    createdBy: row.created_by as string,
    createdAt: row.created_at as string,
    updatedAt: row.updated_at as string,
    parentAgent: (row.parent_agent as string) ?? null,
    spawnDepth: (row.spawn_depth as number) ?? 0,
    agentType: ((row.agent_type as string) ?? 'standard') as 'standard' | 'persistent' | 'system',
    classification: ((row.classification as string) ?? 'apprentice') as 'sensei' | 'ronin' | 'apprentice',
    groupId: (row.group_id as string) ?? null,
    maxRuntime: (row.max_runtime as number) ?? null,
    timeoutAt: (row.timeout_at as string) ?? null,
    permissions: JSON.parse((row.permissions as string) || '{}'),
    toolsPolicy: JSON.parse((row.tools_policy as string) || '{}'),
    equippedTechniques: JSON.parse((row.equipped_techniques as string) || '[]'),
    taskId: (row.task_id as string) ?? null,
    messageCount: msgCount,
    uptime,
    model,
    dreamerIgnore: row.dreamer_ignore === 1,
  };
}

// POST /archive — hide terminated agents older than N days (default 7)
agentsRouter.post('/archive', (c) => {
  const db = getDb();
  const days = 7;
  const cutoff = new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

  // Mark old terminated agents as archived by setting agent_type to 'archived'
  const result = db.prepare(`
    UPDATE agents SET agent_type = 'archived', updated_at = datetime('now')
    WHERE status = 'terminated' AND updated_at < ? AND classification != 'sensei' AND agent_type != 'archived'
  `).run(cutoff);

  logger.info('Archived old terminated agents', { count: result.changes, cutoffDays: days });
  return c.json({ ok: true, data: { archived: result.changes } });
});

export { agentsRouter };
