-- 183 (t110, BACKLOG "round-3-red" + "round-2-red"): THE REPORT LEARNS WHICH ASK IT ANSWERS.
--
-- The round-2 investigation said it in one sentence and three rounds have now paid interest on
-- it: the withdrawal window is RAW CONTAINMENT, and the durable fix is a column binding the
-- report to the ask it was opened for. This is that column.
--
-- ════════════════════════════════════════════════════════════════════════════════════════
-- WHAT CONTAINMENT COSTS, AND WHY A COLUMN IS NOT A TIDINESS PREFERENCE
-- ════════════════════════════════════════════════════════════════════════════════════════
--
-- `dojo_report` is the only user-facing door in the engine that writes no `deliveries` row, so
-- the "answered" stamp and the preview card it announced have no edge between them. Cancel the
-- card and every read that lists or quotes settled asks keeps serving the claim as an engine
-- record, under "do NOT re-execute this work". `report/withdrawn-claim.ts` closes that, and it
-- closes it by asking a question no schema could answer: WHICH REPORTS ARE NAMED NEAR THIS
-- ANSWER. Near is three arms (the stamp's own turn, one turn back, and the `seq` span between
-- ask and answer) and one `LIKE '%' || substr(r.id, 1, 8) || '%'` per report row.
--
-- That predicate was measured honestly and it is NOT a false-green: over the live corpus of
-- 4,242 answered asks it voids 13, and all 13 are genuine report asks. But the cost is written
-- into its own header as five accepted over-void shapes and one unclosed residual:
--
--   * two asks batched into one turn void TOGETHER, because `setAnswerMessageId` stamps every
--     row it served;
--   * the span arm voids anything answered between the pair;
--   * a report named in ANOTHER conversation inside the span voids a dashboard ask;
--   * the turn arm reaches rows written BEFORE the ask;
--   * the one-turn reach adds the previous turn's rows;
--   * AND THE RESIDUAL: a restatement that names no id and is two or more turns from any row
--     that does is not bound at all. The header says what closing it properly wants, by name:
--     "the `dojo_reports.ask_id` column the round-2 investigation named, not a wider text rule."
--
-- Every one of those six is the same defect wearing six hats: the platform MINTED the report
-- inside a turn that was answering a specific ask, knew exactly which ask that was, and wrote
-- it down nowhere. Containment then reconstructs it afterwards from proximity, which is why it
-- cannot be both complete and narrow — widen the window and it voids a question about
-- centimetres; narrow it and the no-id restatement escapes.
--
-- ════════════════════════════════════════════════════════════════════════════════════════
-- WHAT GOES IN THE COLUMN
-- ════════════════════════════════════════════════════════════════════════════════════════
--
-- `messages.id` of the ASK the report was opened in response to — the same row whose
-- `answer_message_id` the answered edge reads, so the binding is expressed in the vocabulary
-- that already decides answeredness rather than a second one invented here. `report/store.ts`
-- resolves it at `createReport` (the `gather` phase, the one call that mints the id) as the
-- agent's latest `role='user'` row, which is the ask the turn is answering; the answer row does
-- not exist yet at that moment, which is precisely why the ask is the durable end to bind.
--
-- NULLABLE, AND NOTHING IS BACKFILLED. A historical row's ask is not recoverable: the only
-- evidence of it is the proximity containment already reads, so a backfill would write
-- containment's GUESS into the column built to replace guessing — and then the column could
-- never be trusted as a binding again. NULL reads as "this row predates the binding", which is
-- exactly true, and `withdrawn-claim.ts` keeps the containment arm for those rows and says so
-- in a log line. The two arms coexist permanently by design: bound rows get the narrow answer,
-- legacy rows get the old one, and no row gets a fabricated binding.
--
-- STABLE-BRIDGE: additive and NULL-safe. One new nullable column, two indexes, no rewrite of a
-- single existing row, no reader that breaks on NULL. An upgrade-day box crosses this without
-- touching its report history.
--
-- ════════════════════════════════════════════════════════════════════════════════════════
-- THE ONE INDEX THIS MIGRATION ADDS — AND THE ONE IT DOES NOT, BECAUSE 171 ALREADY DID
-- ════════════════════════════════════════════════════════════════════════════════════════
--
-- `idx_dojo_reports_ask_id` serves the new bound lookup: given one ask, has it a report, and is
-- that report still standing. It runs on every answered-ask read that gets past the cheap gate,
-- and it is the only index this migration creates.
--
-- ⚠ `idx_dojo_reports_agent_id` IS NOT HERE, AND THE FIRST CUT OF THIS FILE WAS WRONG ABOUT IT.
-- The BACKLOG carries "the `dojo_reports` agent_id index" as its own line, and this migration
-- was first written to pay it — arguing the index into existence as new, and quoting
-- `withdrawn-claim.ts`'s "when that table stops being tiny, index `agent_id`" as an unpaid note.
-- IT WAS ALREADY PAID. `171_report_read_indexes.sql:100` creates it, and 171's header names the
-- reader it was bought FOR in so many words — "`idx_dojo_reports_agent_id` — WRITER: nobody
-- (derived). READER it is FOR: `report/withdrawn-claim.ts`'s `agentHasWithdrawnReport`" — with
-- its own answer to the tiny-table note one line above the statement: "Bought before the scan
-- stops being tiny." 171 also owns the plan clause that keeps it alive
-- (`db/__tests__/migration-171-report-read-indexes.test.ts`, which pins the index by name).
--
-- So a second `CREATE INDEX IF NOT EXISTS` here would be DEAD SQL: harmless on every box, and
-- permanently misleading, because a migration's text cannot be corrected after it merges. The
-- statement is gone and the ownership is recorded instead. The EXPLAIN QUERY PLAN clause for
-- the cheap gate lives with this lane's work but pins 171's index, which is the one the planner
-- actually chooses; `withdrawn-claim.ts`'s own cost paragraph is corrected in the same commit,
-- because it still claimed there was no index on `agent_id` long after 171 shipped one.
--
-- The `status` column is deliberately NOT in either index, and that part of the first cut stands.
-- The gate's own header argues it: the index-using form of the predicate is
-- `status IN (<the standing values>)`, and a closed IN-list cannot express "anything this
-- release does not recognise is treated as withdrawn", which is the safe direction `store.ts`'s
-- rule 4 takes for an unknown status. So `agent_id` narrows to this agent's handful of rows and
-- the open-ended status test is applied to those — the whole point being that it stays
-- open-ended.

ALTER TABLE dojo_reports ADD COLUMN ask_id TEXT;

CREATE INDEX IF NOT EXISTS idx_dojo_reports_ask_id ON dojo_reports (ask_id);
